# =====================
# Telegram notificatie (Primary)
# =====================
- platform: telegram
  name: telegram_primary
  api_key: !secret telegram_token
  chat_id: "8255991553"

# =====================
# Email notificatie (Backup)
# =====================
- platform: smtp
  name: email_backup
  server: smtp.gmail.com
  port: 587
  sender: jouw.email@gmail.com
  encryption: starttls
  username: jouw.email@gmail.com
  password: !secret email_password
  recipient:
    - ontvanger1@gmail.com

# =====================
# Signal notificatie (Extra)
# =====================
- platform: rest
  name: signal_notify
  resource: "https://api.signal.org/v1/messages"
  method: POST
  headers:
    Authorization: "Bearer !secret signal_token"
    Content-Type: "application/json"